connection: &connection
  adapter: mysql2
  host: localhost
  pool: 5
  timeout: 5000
  username: root
  password: zaqxsw

development:
  <<: *connection
  database: bugzilla

test: &test
  <<: *connection
  database: bugzilla