development:
  adapter: postgresql
  encoding: unicode
  database: bugzilla
  pool: 5
  username: postgres
  password: password
test:
  adapter: postgresql
  encoding: unicode
  database: bugzilla
  pool: 5
  username: postgres
  password: password
production:
  adapter: postgresql
  encoding: unicode
  database: bugzilla
  pool: 5
  username: postgres
  password: password